{% set name = "cupy" %}
{% set version = "9.3.0" %}
{% set sha256 = "7c3127219ef315722037f4cec54f35773602de911c1ae4a2b22f1692cf4ce71c" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% set cuda_minor = 0 %}
{% set cuda_major_minor = (0, 0) %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.2").split(".")[0]|int %}
{% set cuda_minor = environ.get("cuda_compiler_version", "11.2").split(".")[1]|int %}
{% set cuda_major_minor = (cuda_major, cuda_minor) %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [(not win64 and not linux64) or ppc64le or cuda_compiler_version != "11.3" or py != 39]
#  script_env:
#    # for some reason /usr/local/cuda is not added to $PATH in ppc64le's docker image
#    - CUDA_HOME  # [ppc64le]
  script:
#    # CuPy default detects CUDA from nvcc, but on Conda-Forge's dockers nvcc lives in a different place...
#    # With conda-forge/nvcc-feedstock#58, CUDA_PATH is set correctly
    - export CFLAGS="$CFLAGS -L${PREFIX}/lib/stubs"                              # [linux]
    - export NVCC=$(which nvcc)                                                  # [linux]
    - export CUDA_PATH=$PREFIX                                                   # [linux]
    - echo "nvcc is $NVCC, CUDA path is $CUDA_PATH"                              # [linux]
    - call set "CUDA_PATH=%PREFIX%"                                                                            # [win]
    - for /f "tokens=* usebackq" %%f in (`where nvcc`) do (set "dummy=%%f" && call set "NVCC=%%dummy:\=\\%%")  # [win]
    - echo "nvcc is %NVCC%, CUDA path is %CUDA_PATH%"                                                          # [win]
    #{% if cuda_major == 11 %}
    #- export CUSPARSELT_PATH=$PREFIX  # [linux64]
    #{% endif %}
    #{% if cuda_major_minor >= (10, 1) %}
    #- export CUGRAPH_PATH=$PREFIX  # [linux64]
    #{% endif %}
    # Workaround __ieee128 error; see https://github.com/LLNL/blt/issues/341
    - export NVCC="$NVCC -Xcompiler -mno-float128"  # [ppc64le]

    - {{ PYTHON }} -m pip install . --no-deps -vv
    - if errorlevel 1 exit 1  # [win]

    # copy activate/deactivate scripts
    - mkdir -p "${PREFIX}/etc/conda/activate.d"                                               # [linux]
    - cp "${RECIPE_DIR}/activate.sh" "${PREFIX}/etc/conda/activate.d/cupy_activate.sh"        # [linux]
    - mkdir -p "${PREFIX}/etc/conda/deactivate.d"                                             # [linux]
    - cp "${RECIPE_DIR}/deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/cupy_deactivate.sh"  # [linux]
    - if not exist %PREFIX%\etc\conda\activate.d mkdir %PREFIX%\etc\conda\activate.d          # [win]
    - copy %RECIPE_DIR%\activate.bat %PREFIX%\etc\conda\activate.d\cupy_activate.bat          # [win]
    - if not exist %PREFIX%\etc\conda\deactivate.d mkdir %PREFIX%\etc\conda\deactivate.d      # [win]
    - copy %RECIPE_DIR%\deactivate.bat %PREFIX%\etc\conda\deactivate.d\cupy_deactivate.bat    # [win]

    # enable CuPy's preload mechanism
    - mkdir -p "${SP_DIR}/cupy/.data/"                                                                                     # [linux]
    - cp ${RECIPE_DIR}/preload_config/linux64_cuda{{ cuda_compiler_version }}_wheel.json ${SP_DIR}/cupy/.data/_wheel.json  # [linux]
    - if not exist %SP_DIR%\cupy\.data mkdir %SP_DIR%\cupy\.data                                                           # [win]
    - copy %RECIPE_DIR%\preload_config\win64_cuda{{ cuda_compiler_version }}_wheel.json %SP_DIR%\cupy\.data\_wheel.json    # [win]
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux]
    - '*/nvcuda.dll'  # [win]
  #ignore_run_exports_from:
    #- cudnn
    #- nccl  # [linux]
    #- cutensor  # [win or cdt_name == "cos7"]
    #{% if cuda_major == 11 %}
    #- cusparselt  # [linux64]
    #{% endif %}
    #{% if cuda_major_minor >= (10, 1) %}
    #- libcugraph  # [linux64]
    #{% endif %}
  #ignore_run_exports:
    #{% if cuda_major_minor >= (10, 1) %}
    ## libcugraph -> librmm -> (spdlog, thrust)
    #- spdlog  # [linux]
    #- thrust  # [linux]
    #{% endif %}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cuda-nvcc
    - sysroot_linux-64 2.17  # [linux and cdt_name == "cos7"]

  host:
    - python
    - pip
    - setuptools
    - cython >=0.29.22,<3
    - fastrlock >=0.5
    #- cudnn
    #- nccl  # [linux]
    #- cutensor  # [win or cdt_name == "cos7"]
    #{% if cuda_major == 11 %}
    #- cusparselt  # [linux64]
    #{% endif %}
    #{% if cuda_major_minor >= (10, 1) %}
    #- libcugraph  # [linux64]
    #{% endif %}
    - cuda-nvcc  # for crt/host_defines.h
    - cuda-cudart
    - cuda-nvrtc
    - cuda-nvprof  # for cuda_profiler_api.h
    - cuda-thrust
    - libcublas
    - libcufft
    - libcurand
    - libcusolver
    - libcusparse

  run:
    - python
    - setuptools
    - fastrlock >=0.5
    - numpy >=1.17

  run_constrained:
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17      # [linux and cdt_name == "cos7"]
    - scipy >=1.4
    - optuna >=2
    #- {{ pin_compatible('cudnn') }}
    #- {{ pin_compatible('nccl') }}  # [linux]
    #- {{ pin_compatible('cutensor', lower_bound='1.3') }}
    #{% if cuda_major == 11 %}
    #- {{ pin_compatible('cusparselt') }}  # [linux64]
    #{% endif %}
    #{% if cuda_major_minor >= (10, 1) %}
    #- {{ pin_compatible('libcugraph') }}  # [linux64]
    #{% endif %}

test:
  requires:
    - pytest
    - mock
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cuda-nvcc
    #- scipy >=1.0,<1.1  <-- cause error

  source_files:
    - tests

about:
  home: https://cupy.dev/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CuPy is an implementation of a NumPy-compatible multi-dimensional array on CUDA.
  dev_url: https://github.com/cupy/cupy/
  doc_url: https://docs.cupy.dev/en/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - leofang
    - kmaehashi
    - asi1024
    - emcastillo
    - toslunar
