{% set name = "cupy" %}
{% set version = "6.5.0" %}
{% set sha256 = "0454ff66301ec2b1bab775ed655d8a3a75ae00bb2a37ca6c265f4fa2c3102edb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cupy/cupy/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not (linux64 and cuda_compiler_version != "None")]
  script: "{{ PYTHON }} -m pip install . -vv"
  missing_dso_whitelist:
    - "*/libcuda.*"

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}

  host:
    - python
    - pip
    - setuptools
    - cython >=0.24.0
    - cudnn
    - fastrlock >=0.3
    - nccl

  run:
    - python
    - setuptools
    - cudnn
    - fastrlock >=0.3
    - numpy >=1.9.0
    - six >=1.9.0

test:
  requires:
    - pytest
    - mock
  source_files:
    - tests

about:
  home: https://cupy.chainer.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CuPy is an implementation of a NumPy-compatible multi-dimensional array on CUDA.

extra:
  recipe-maintainers:
    - jakirkham
    - leofang
