{% set name = "cupy" %}
{% set version = "12.0.0" %}
{% set sha256 = "61ddbbef73d50d606bd5087570645f3c91ec9176c2566784c1d486d6a3404545" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% set cuda_minor = 0 %}
{% set cuda_major_minor = (0, 0) %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.2").split(".")[0]|int %}
{% set cuda_minor = environ.get("cuda_compiler_version", "11.2").split(".")[1]|int %}
{% set cuda_major_minor = (cuda_major, cuda_minor) %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - support_new_cuda_layout.diff  # [linux]

build:
  number: 1
  skip: true  # [not linux64 or cuda_compiler_version == "None"]  # TODO: turn on other platforms once cuda-nvcc is ready
  script:
    - export NVCC="$(which nvcc) -I$PREFIX/targets/x86_64-linux/include"         # [linux]
    - export CUDA_PATH=$PREFIX/targets/x86_64-linux                              # [linux64]
    - export CUDA_PATH=$PREFIX/targets/aarch64-linux                             # [aarch64]
    - export CUDA_PATH=$PREFIX/targets/ppc64le-linux                             # [ppc64le]
    - echo "nvcc is $NVCC, CUDA path is $CUDA_PATH"                              # [linux]
    - export CFLAGS="$CFLAGS -I$CUDA_PATH/include -I$BUILD_PREFIX/targets/x86_64-linux/include -L$CUDA_PATH/lib/stubs"  # [linux]
    - for /f "tokens=* usebackq" %%f in (`where nvcc`) do (set "dummy=%%f" && call set "NVCC=%%dummy:\=\\%%")  # [win]
    # we use this WAR until we figure out how to proceed with conda-forge/nvcc-feedstock#88
    - set "NVCC=%NVCC% --use-local-env"  # [win64]
    - echo "nvcc is %NVCC%, CUDA path is %CUDA_PATH%"  # [win]
    {% if cuda_major_minor >= (11, 2) %}
    - export CUSPARSELT_PATH=$PREFIX  # [linux64 or win]
    {% endif %}
    # Workaround __ieee128 error; see https://github.com/LLNL/blt/issues/341
    - export NVCC="$NVCC -Xcompiler -mno-float128"  # [ppc64le]

    - {{ PYTHON }} -m pip install . --no-deps -vv
    - if errorlevel 1 exit 1  # [win]

    # copy activate/deactivate scripts
    - mkdir -p "${PREFIX}/etc/conda/activate.d"                                               # [linux]
    - cp "${RECIPE_DIR}/activate.sh" "${PREFIX}/etc/conda/activate.d/cupy_activate.sh"        # [linux]
    - mkdir -p "${PREFIX}/etc/conda/deactivate.d"                                             # [linux]
    - cp "${RECIPE_DIR}/deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/cupy_deactivate.sh"  # [linux]
    - if not exist %PREFIX%\etc\conda\activate.d mkdir %PREFIX%\etc\conda\activate.d          # [win]
    - copy %RECIPE_DIR%\activate.bat %PREFIX%\etc\conda\activate.d\cupy_activate.bat          # [win]
    - if not exist %PREFIX%\etc\conda\deactivate.d mkdir %PREFIX%\etc\conda\deactivate.d      # [win]
    - copy %RECIPE_DIR%\deactivate.bat %PREFIX%\etc\conda\deactivate.d\cupy_deactivate.bat    # [win]

    # enable CuPy's preload mechanism
    - mkdir -p "${SP_DIR}/cupy/.data/"                                                                                     # [linux]
    - if not exist %SP_DIR%\cupy\.data mkdir %SP_DIR%\cupy\.data                                                           # [win]
    {% if cuda_major_minor >= (11, 2) %}
    - cp ${RECIPE_DIR}/preload_config/linux64_cuda11_wheel.json ${SP_DIR}/cupy/.data/_wheel.json                           # [linux]
    - copy %RECIPE_DIR%\preload_config\win64_cuda11_wheel.json %SP_DIR%\cupy\.data\_wheel.json                             # [win]
    {% else %}
    - cp ${RECIPE_DIR}/preload_config/linux64_cuda{{ cuda_compiler_version }}_wheel.json ${SP_DIR}/cupy/.data/_wheel.json  # [linux]
    - copy %RECIPE_DIR%\preload_config\win64_cuda{{ cuda_compiler_version }}_wheel.json %SP_DIR%\cupy\.data\_wheel.json    # [win]
    {% endif %}
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux]
    - '*/nvcuda.dll'  # [win]
  ignore_run_exports:
  #  - cudnn
  #  - nccl  # [linux]
  #  - cutensor
  #  {% if cuda_major_minor >= (11, 2) %}
  #  - cusparselt  # [linux64 or win]
  #  {% endif %}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    #- {{ compiler("cuda") }}
    - cuda-nvcc
    - sysroot_linux-64 2.17  # [linux64]

  host:
    - python
    - pip
    - setuptools
    - cython >=0.29.22,<3
    - fastrlock >=0.5
  #  - cudnn >=7.6
  #  - nccl >=2.8  # [linux]
  #  - cutensor >=1.4
  #  {% if cuda_major_minor >= (11, 2) %}
  #  - cusparselt 0.2.0.*  # [linux64 or win]
  #  {% endif %}
    # TODO: clean up
    - cuda-driver-dev
    - cuda-cudart-dev
    - cuda-nvrtc-dev
    - cuda-nvtx-dev
    - cuda-profiler-api
    - cuda-cccl_{{ target_platform }}
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    - cuda-version {{ cuda_compiler_version }}

  run:
    - python
    - {{ pin_compatible('fastrlock', max_pin='x.x') }}
    - numpy >=1.21
    - cuda-version >={{ cuda_major }}.0,<{{ cuda_major+1 }}

  run_constrained:
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17      # [linux]
    - scipy >=1.7
    - optuna >=3
  #  - {{ pin_compatible('cudnn') }}
  #  - {{ pin_compatible('nccl') }}  # [linux]
  #  - {{ pin_compatible('cutensor', lower_bound='1.3') }}
  #  {% if cuda_major_minor >= (11, 2) %}
  #  - {{ pin_compatible('cusparselt', max_pin='x.x') }}  # [linux64 or win]
  #  {% endif %}

test:
  requires:
    # - pytest
    - cuda-driver-dev  # need the libcuda stub for import test

  source_files:
    - tests

about:
  home: https://cupy.dev/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    CuPy: NumPy & SciPy for GPU
  dev_url: https://github.com/cupy/cupy/
  doc_url: https://docs.cupy.dev/en/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - leofang
    - kmaehashi
    - asi1024
    - emcastillo
    - toslunar
