{% set name = "cupy" %}
{% set version = "7.3.0" %}
{% set sha256 = "cdd37a0cfcda0ac534ab00c48aee2ea9ab0fc706f74cad24445642095b81479d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/cupy/cupy/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      # Include full CUDA 10.2 support: https://github.com/cupy/cupy/pull/3218
      - fixes_3218.diff

  # CUB support has too many bugs, let us wait for a bit longer
  ## 1. The CUB support has been extensively tested with v1.8.0, so we should pin it here
  ## 2. This dependency should be removed once CuPy bundles CUB (cupy/cupy#2584)
  #- url: https://github.com/NVlabs/cub/archive/v1.8.0.tar.gz
  #  sha256: 025658f4c933cd2aa8cc88a559d013338d68de3fa639cc1f2b12cf61dc759667
  #  folder: cub_v1.8.0  # so the source code is in cupy/cub_v1.8.0

build:
  number: 0
  # temporarily disable PyPy build (conda-forge/cupy-feedstock#43)
  skip: True  # [python_impl == "pypy"]
  skip: True  # [cuda_compiler_version in (undefined, "None")]
  script:
    # CUDA 10.1 moves some headers to `/usr/include`
    # So add that location last in the header search paths
    - export CFLAGS="${CFLAGS} -I/usr/include"
    - export CPPFLAGS="${CPPFLAGS} -I/usr/include"
    - export CXXFLAGS="${CXXFLAGS} -I/usr/include"
    #- export CUB_PATH=${PWD}/cub_v1.8.0  # TODO(leofang): remove this
    - "{{ PYTHON }} -m pip install . -vv"
  missing_dso_whitelist:
    - "*/libcuda.*"

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}

  host:
    - python
    - pip
    - setuptools
    - cython >=0.24.0
    - fastrlock >=0.3
    - cudnn
    - nccl

  run:
    - python
    - setuptools
    - fastrlock >=0.3
    - numpy >=1.9.0
    - six >=1.9.0
    # - cudnn  <-- added via run_export
    # - nccl   <-- added via run_export

test:
  requires:
    - pytest
    - mock
  source_files:
    - tests

about:
  home: https://cupy.chainer.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CuPy is an implementation of a NumPy-compatible multi-dimensional array on CUDA.

extra:
  recipe-maintainers:
    - jakirkham
    - leofang
    - kmaehashi
    - beam2d
    - asi1024
    - emcastillo
    - hvy
    - niboshi
    - toslunar
