# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic



matrix:
  include:
    - env: CONFIG=linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.2
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.7.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.2
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.2
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.2
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.2
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.0
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.7.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.0
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.0
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.0
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.0
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.1
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.7.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.1
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.1
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.1
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64-cuda:11.1
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.7.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version8cuda_compiler_version10.2cxx_compiler_version8python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version8cuda_compiler_version10.2cxx_compiler_version8python3.7.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version8cuda_compiler_version10.2cxx_compiler_version8python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version8cuda_compiler_version10.2cxx_compiler_version8python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version8cuda_compiler_version10.2cxx_compiler_version8python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.0
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.7.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.0
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.0
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.0
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.0cxx_compiler_version9python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.0
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.1
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.7.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.1
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.1
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.1
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_c_compiler_version9cuda_compiler_version11.1cxx_compiler_version9python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le-cuda:11.1
      os: linux
      arch: ppc64le
      dist: focal

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})
  - if [[ "${TRAVIS_PULL_REQUEST:-}" == "false" ]]; then export IS_PR_BUILD="False"; else export IS_PR_BUILD="True"; fi


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then CONDA_FORGE_DOCKER_RUN_ARGS="--network=host --security-opt=seccomp=unconfined" travis_wait 120 ./.scripts/run_docker_build.sh; fi