azure:
  free_disk_space: true
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
idle_timeout_minutes: 120
os_version:
  linux_64: cos7
  linux_aarch64: cos7
  linux_ppc64le: cos7
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native
