conda_forge_output_validation: true
os_version:
  linux_64: cos7
  linux_aarch64: cos7
  linux_ppc64le: cos7
provider:
  linux_ppc64le: default
  linux_aarch64: default
idle_timeout_minutes: 120
github:
  branch_name: main
  tooling_branch_name: main
