conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
idle_timeout_minutes: 120
os_version:
  linux_64: cos7
  linux_aarch64: cos7
  linux_ppc64le: cos7
build_platform:
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
conda_build:
  pkg_format: '2'
test: native
azure:
  store_build_artifacts: true
