build_platform:
  linux_ppc64le: linux_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
idle_timeout_minutes: 120
provider:
  linux_aarch64: default
  linux_ppc64le: azure
test: native
workflow_settings:
  free_disk_space: quick
  pagefile_size:
  - os: linux
    value: 8
  - os: win
    value: 16
