azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 8GiB
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
      MINIFORGE_HOME: C:\\Miniforge
      SET_PAGEFILE: 'True'
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
idle_timeout_minutes: 120
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native
